### ISSUE TITLE
Illegal instruction (core dumped) when running "./nlt_build.exe -h"

### ISSUE THREAD

**Issue by foudrer** [Terark/terark-wiki-zh_cn#1]
Hi,
   when I use Terark command tools, it shows "Illegal instruction (core dumped)".
   My CPU support sse4_1 & sse4_2 & popcnt, and I download terark-fsa_all-Linux-x86_64-g++-5.3-bmi2-1.tgz to run the Terark command tools.
   Do you have some suggestions?
  Thank you!

**Comment by jojo59516** [comment]
We use BMI2 instructions. Please try bmi2-0 ver.

**Comment by foudrer** [comment]
I use the bmi2-0 version. but it is always wrong, show as follows: 

[root@localhost terark-fsa_all-Linux-x86_64-g++-5.3-bmi2-0]# ls
bin  include  lib  package.buildtime.txt  samples  zsrch
[root@localhost terark-fsa_all-Linux-x86_64-g++-5.3-bmi2-0]# cd bin/
[root@localhost bin]# ls
ac_build.exe          dawg_build.exe  ftrie_build.exe         nlt_benchmark.exe  revline.exe
adfa_build.exe        ddfa_stat.exe   kvbin_build.exe         nlt_build.exe      splitkv.exe
adfa_stat.exe         dfa2vm.exe      lazy_union_dfa.exe      nlt_extract.exe    text_key_val_to_kvbin.exe
adfa_unzip.exe        dfa_union.exe   multi_col_db_build.exe  pinyin_build.exe   zbs_build.exe
blob_store_bench.exe  fplcat.exe      nlt_archive.exe         regex_build.exe    zbs_unzip.exe
[root@localhost bin]# ./nlt_build.exe -h
Illegal instruction (core dumped)

Do you have any ideas?

**Comment by mm304321141** [comment]
run
```
cat /proc/cpuinfo | sed -n '/^flags\s*:\s*/s/^[^:]*:\s*//p' | uniq | tr 'A-Z' 'a-z' | sed 's/\s\+/\n/g'
```
and tell us the result pls

**Comment by foudrer** [comment]
The result of the command is as follows:
fpu
vme
de
pse
tsc
msr
pae
mce
cx8
apic
sep
mtrr
pge
mca
cmov
pat
pse36
clflush
dts
acpi
mmx
fxsr
sse
sse2
ss
ht
syscall
nx
rdtscp
lm
constant_tsc
arch_perfmon
pebs
bts
nopl
xtopology
tsc_reliable
nonstop_tsc
aperfmperf
pni
pclmulqdq
ssse3
cx16
sse4_1
sse4_2
popcnt
aes
hypervisor
lahf_lm
ida
arat
dtherm

**Comment by rockeet** [comment]
It seems your CPU is an old AMD cpu, we compiled `bmi2-0` version with gcc `-march=corei7`, this is an old intel CPU. An older CPU compatible with both AMD and Intel may be too old.

So, do you have a newer machine?

And, have you updated `LD_LIBRAY_PATH` after convert from `bmi2-1` to `bmi2-0`?

**Comment by foudrer** [comment]
It is an old Intel CPU ( Intel(R) Xeon(R) CPU E5620  @ 2.40GHz ), and I just put the libterark*.so(bmi2-0) into the system lib dir

**Comment by rockeet** [comment]
So, you need a newer CPU...
